name: "Test"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: "Run Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Use GitHub Actions"
        uses: actions/checkout@v1
      - name: "Use Node.js 12.x"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: "Install Package"
        run: "yarn"
      - name: "Run Test"
        run: "npm test"
  coverage:
    needs: [ test ]
    name: "Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Jest Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
